---

- hosts: all
  roles:
    - { role: pre-install, tags: ["pre-install"] }

- hosts: master
  roles:
    - { role: common, tags: ["registry", "router", "metrics", "logging"] }
    - { role: registry, tags: ["registry"] }
    - { role: router, tags: ["router"] }
    - { role: metrics, tags: ["metrics"] }
    - { role: logging, tags: ["logging"] }

- hosts: repository
  roles:
    - { role: repository, tags: ["repository"] }

#
# - hosts: infra
#   roles:
#     - { role: registry, tags: ["registry"] }
#     - { role: router, tags: ["router"] }
#     - { role: metrics, tags: ["metrics"] }
#     - { role: logging, tags: ["logging"] }
