---
- hosts: master
  roles:
    - { role: registry, tags: ["registry"] }
    - { role: router, tags: ["router"] }
    - { role: metrics, tags: ["metrics"] }
    - { role: logging, tags: ["logging"] }

# - hosts: all
#   roles:
#     - { role: registry, tags: ["registry"] }
#     - { role: router, tags: ["router"] }
#     - { role: metrics, tags: ["metrics"] }
#     - { role: logging, tags: ["logging"] }
#
# - hosts: infra
#   roles:
#     - { role: registry, tags: ["registry"] }
#     - { role: router, tags: ["router"] }
#     - { role: metrics, tags: ["metrics"] }
#     - { role: logging, tags: ["logging"] }
