---
- hosts: master
  tasks:
   - include_vars: vars.yml

   - name: Checking if registry is already installed
     shell: oc get all -l docker-registry=default -n default
     register: registry_installed

   - name: Changing master to schedulable
     shell: oadm manage-node {{master_name}}.{{domain}} --schedulable=true
     when: registry_installed.stdout == ''

   - name: Grep master label
     shell: oc describe node {{master_name}}.{{domain}} | grep Label | awk '{print $2}'
     register: master_label
     when: registry_installed.stdout == ''

   - name: Install Registry
     shell: oc project default && oadm registry --service-account=registry  --config=/etc/origin/master/admin.kubeconfig  --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --mount-host=/registry --selector={{master_label.stdout}}
     failed_when: master_label.stdout == ''
     when: registry_installed.stdout == ''
     notify:
       - Create and correct registry folder permissions

  handlers:
    - name: Create and correct registry folder permissions
      shell: mkdir -p /registry && chown 1001:root /registry
    - include: handlers/handlers.yaml
