---
- include_vars: ../vars.yml

- name: Checking if metrics is already installed
  shell: oc get all --selector="metrics-infra" -n openshift-infra
  register: metrics_installed

- name: Pulling metrics images
  shell: docker pull {{ item }}
  when: metrics_installed.stdout == '' and uninstall is undefined
  with_items:
   - registry.access.redhat.com/openshift3/metrics-heapster:3.2.1
   - registry.access.redhat.com/openshift3/metrics-hawkular-metrics:3.2.1
   - registry.access.redhat.com/openshift3/metrics-cassandra:3.2.1

- name: Changing to project openshift-infra
  shell: oc project openshift-infra
  when: metrics_installed.stdout == '' and uninstall is undefined

- name: Creating service account
  shell: 'echo -e "apiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: metrics-deployer\nsecrets:\n- name: metrics-deployer" | oc create -f -'
  when: metrics_installed.stdout == '' and uninstall is undefined

- name: Adjusting permissions
  shell: oadm policy add-role-to-user edit system:serviceaccount:openshift-infra:metrics-deployer && oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:openshift-infra:heapster
  when: metrics_installed.stdout == '' and uninstall is undefined

- name: Creating secrets
  shell: oc secrets new metrics-deployer nothing=/dev/null
  when: metrics_installed.stdout == '' and uninstall is undefined

- name: Creating metrics deployer
  shell: oc new-app -f /usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml -p HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.{{subdomain}} -p USE_PERSISTENT_STORAGE=false
  when: metrics_installed.stdout == '' and uninstall is undefined

- name: Editing master-config.yaml with metrics url
  lineinfile: "dest=/etc/origin/master/master-config.yaml state=present backup=yes insertbefore='logout' line='  metricsPublicURL: https://hawkular-metrics.{{subdomain}}/hawkular/metrics'"
  when: metrics_installed.stdout == '' and uninstall is undefined
  notify:
    - Validate master-config

# Uninstalling

- name: Cleaning up metrics
  shell: oc project openshift-infra && oc delete all --selector="metrics-infra" && oc delete sa --selector="metrics-infra" && oc delete templates --selector="metrics-infra" && oc delete secrets --selector="metrics-infra" && oc delete pvc --selector="metrics-infra"  && oc delete sa metrics-deployer && oc delete secret metrics-deployer
  when: metrics_installed.stdout != "" and uninstall is not undefined
  ignore_errors: yes

  # - name: Remove metrics images
  #   shell: docker rmi {{ item }}
  #   when: metrics_installed.stdout != "" and remove_images_on_cleanup == True
  #   tags:
  #       - metrics
  #   with_items:
  #    - registry.access.redhat.com/openshift3/metrics-heapster:3.2.1
  #    - registry.access.redhat.com/openshift3/metrics-hawkular-metrics:3.2.1
  #    - registry.access.redhat.com/openshift3/metrics-cassandra:3.2.1
