- name: Get docker info
  command: docker info
  register: docker_info

- name: Show docker info
  debug:
    var: docker_info.stdout_lines

- name: Remove exited and dead containers
  shell: "docker ps -a | awk '/Exited|Dead/ {print $1}' | xargs --no-run-if-empty docker rm"
  ignore_errors: yes

- name: Remove dangling docker images
  shell: "docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi"
  ignore_errors: yes

- name: Remove non-running docker images
  shell: "docker images | grep -v -e registry.access.redhat.com | awk '{print $3}' | xargs --no-run-if-empty docker rmi 2>/dev/null"
  ignore_errors: yes

- name: Remove non-running duplicated docker images
  shell: "docker images | grep -v -e registry.access.redhat.com | awk '{print $1}' | xargs --no-run-if-empty docker rmi 2>/dev/null"
  ignore_errors: yes

- name: Remove docker images <none>
  shell: "docker images | egrep "^<none>" | awk '{print $3}' | xargs --no-run-if-empty docker rmi 2>/dev/null"
  ignore_errors: yes

- name: Get docker info
  command: docker info
  register: docker_info

- name: Show docker info
  debug:
    var: docker_info.stdout_lines

# - name: Remove stopped containers
#   shell: docker rm {{item}} || true
#   with_items:
#     - $(docker ps --filter "status=exited" -q)
#     - $(docker ps | grep Dead | awk 'print $1')

# - name: Remove Old Images
#   shell: docker rmi {{item}} || true
#   with_items:
#     - $(docker images | grep 172.30 | awk '{print $1}')
#     - $(docker images | grep 172.30 | awk '{print $3}')
#     - $(docker images | egrep '^<none>' | awk '{print $3}')
