---

- name: Checking if logging is already installed
  shell: oc login -u system:admin && oc get all -n logging
  register: logging_installed
  changed_when: False

- name: Installing logging
  include: install.yml
  when: logging_installed.stdout == '' and uninstall is undefined

- name: Uninstalling logging
  include: uninstall.yml
  when: logging_installed.stdout != '' and uninstall is defined

- name: Upgrading logging
  include: upgrade.yml
  when: logging_installed.stdout != '' and upgrade is defined
