---
# Installing
- name: Logging with system:admin
  shell: oc login -u system:admin
  changed_when: False

- name: Checking if router is already installed
  shell: oc get all -l router=router -n default
  register: router_installed
  changed_when: False

- name: Greping master info
  shell: oc get nodes | grep -i $(hostname) | awk '{print $1}'
  register: master_name

- name: Changing master to schedulable
  shell: oadm manage-node {{master_name.stdout}} --schedulable=true

- name: Grep master label
  shell: oc describe node {{master_name.stdout}} | grep Label | awk '{print $2}'
  register: master_label

- name: Install Router
  shell: oc project default && oadm router router --replicas=1  --credentials='/etc/origin/master/openshift-router.kubeconfig' --service-account=router --selector={{master_label.stdout}}
  failed_when: master_label.stdout == ''
  when: not expose_router_metrics

- name: Install Router with metrics
  shell: oc project default && oadm router router --replicas=1  --credentials='/etc/origin/master/openshift-router.kubeconfig' --service-account=router --selector={{master_label.stdout}} --expose-metrics --metrics-image=prom/haproxy-exporter
  failed_when: master_label.stdout == ''
  when: expose_router_metrics

# HA Router

- name: Greping master info
  shell: oc get nodes | grep -i $(hostname) | awk '{print $1}'
  register: master_name

- name: Create service account ipfailover
  shell: oc create serviceaccount ipfailover -n default
  when:

- name: Adjust ipfailover policy
  shell: oadm policy add-scc-to-user privileged system:serviceaccount:default:ipfailover
  when:

- name: Deploy router
  shell: oadm router ha-router --replicas=3 --selector="{{label_router}}"  --labels="{{label_router}}" --credentials=/etc/origin/master/openshift-router.kubeconfig  --service-account=ipfailover

- name: Configura VIP and failover
  shell: oadm ipfailover ipf-ha-router --replicas=2 --watch-port=80 --selector="{{label_router}}"  --virtual-ips="10.245.2.101-105" --credentials=/etc/origin/master/openshift-router.kubeconfig --service-account=ipfailover --create

- name: Creating VIP
  shell: oadm ipfailover ipf-ha-router-us-west --replicas=5 --watch-port=80 --selector="ha-router=geo-us-west"  --virtual-ips="10.245.2.101-105" --credentials=/etc/origin/master/openshift-router.kubeconfig  --service-account=ipfailover --create
