---

- name: Checking if router is already installed
  shell: oc login -u system:admin && oc get all -l router=router -n default
  register: router_installed
  changed_when: False

- name: Installing router
  include: install.yml
  when: router_installed.stdout == '' and uninstall is undefined

- name: Uninstalling router
  include: uninstall.yml
  when: router_installed.stdout != '' and uninstall is defined

- name: Upgrading router
  include: upgrade.yml
  when: router_installed.stdout != '' and upgrade is defined
